# Generated by Django 3.2 on 2021-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
