# Generated by Django 3.2 on 2021-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Information Management', 'IM'), ('Computer Networks', 'CN'), ('Relational Database Management System', 'RDBMS')], max_length=100),
        ),
    ]
